# Generated by Django 5.0.6 on 2024-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='prènom')),
                ('last_name', models.CharField(max_length=50, verbose_name='nom')),
                ('email', models.EmailField(max_length=100, verbose_name='Mail')),
            ],
            options={
                'verbose_name': 'member',
            },
        ),
    ]
