# Generated by Django 5.0.6 on 2024-06-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('creator', models.CharField(max_length=150, verbose_name='Créateur')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Jeu de Plateau',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('author', models.CharField(max_length=150, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'livre',
            },
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('artist', models.CharField(max_length=150, verbose_name='Artiste')),
            ],
            options={
                'verbose_name': 'CD',
            },
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('realizator', models.CharField(max_length=150, verbose_name='Réalisateur')),
            ],
            options={
                'verbose_name': 'DVD',
            },
        ),
    ]
